### ISSUE TITLE
Inquiry about the unit of control input

### ISSUE THREAD

**Issue by khinggan** [scybd/Balancing-Car-Simulation#1]
Thanks for the sharing. I have one question. 
In common situation, the unit of control input, linear velocity m/s and angular velocity rad/s. 
However, I find the display of the max linear velocity is 20m/s. Can the model reach the 20m/s? if not, could you please explain more about the unit of the robot control input? 
Thank you very much. 

谢谢博主分享。
请教一个问题：
通常的键盘控制命令的单位线速度是m/s， 角速度是rad/s。在本代码里，键盘控制命令的单位是什么呢？线速度能够到达20m/s吗？谢谢

**Comment by scybd** [comment]
你好，键盘控制命令的单位就是m/s和rad/s。

**Comment by scybd** [comment]
你好，键盘控制命令的单位是m/s和deg/s。
我相信给它足够的时间线速度能达到20m/s，具体和pid参数以及[输出力矩的范围](https://github.com/scybd/Balancing-Car-Simulation/blob/5b54ee69eddb8593889c0933b33490cbb260c78d/src/balancing_car_control/src/controller.cpp#L65)有关
